token:
  resetUrl: http://localhost:8080/backend/auth/reset?token=
  verifyUrl: http://localhost:8080/backend/auth/verify?token=
  ttl: 300

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/invita
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    password:
    port: 6379

  management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  servlet:
    context-path: /backend
