token:
  resetUrl: http://localhost:4200/#/reset-pass?token=
  verifyUrl: http://localhost:4200/#/confirm-email?token=
  ttl: 300

expirationTimeRefresh: 602400_000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/invita
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    password:
    port: 6379

  management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  servlet:
    context-path: /backend
